#!/usr/bin/env bash

cp hzCmd/stash/apache-activemq-5.13.3-bin.tar.gz .
tar xvf ./apache-activemq-5.13.3-bin.tar.gz
rm apache-activemq-5.13.3-bin.tar.gz
cp hzCmd/stash/activemq.xml apache-activemq-5.13.3/conf

echo "export ACTIVE_MQ_BIN=$(pwd)/apache-activemq-5.13.3/bin" >> ~/.bashrc
echo 'PATH=${PATH}:${ACTIVE_MQ_BIN}' >> ~/.bashrc

cd hzCmd
mvn install:install-file -Dfile=stash/coherence.jar -DgroupId=com.coherence -DartifactId=coherence -Dversion=12.2.1 -Dpackaging=jar
mvn clean install dependency:copy-dependencies
echo "export HZ_CMD_SRC=$(pwd)" >> ~/.bashrc
echo "export HZ_CMD=$(pwd)/bin" >> ~/.bashrc
echo "export HZ_CMD_BIN=$(pwd)/target" >> ~/.bashrc
echo 'PATH="${HZ_CMD}:${PATH}"' >> ~/.bashrc
cd -

git clone https://github.com/Danny-Hazelcast/hzCmd-bench.git
cd hzCmd-bench
mvn clean install

echo "export HZ_CMD_BENCH_SRC=$(pwd)" >> ~/.bashrc
echo "export HZ_CMD_BENCH_BIN=$(pwd)/bin" >> ~/.bashrc
echo 'PATH="${HZ_CMD_BENCH_BIN}:${PATH}"' >> ~/.bashrc
